name: MyWorkflow

on:
  push:
    branches: [main]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - name: Print a greeting
        run: |
          echo "Hello There"
          
      - name: check out code
        uses: actions/checkout@v4
      - name: print content
        run: |
          ls
