name: MyWorkflow file
on:
  push:
    branches: [main]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
    #Step 1 Print a greeting message
    - name: Print a greeting
    run: |
      echo "Hello There"
