name: MyWorkflow

on:
  push:
    branches: [main]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - name: Print a greeting
        run: |
          echo "Hello There"
      #This is where I checkout my code
      - name: check out code
        uses: actions/checkout@v4
      - name: print content of repo
        run: |
          ls

      #This is where I install python
      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: check version of python
        run: |
          python --version
      
      #Installing dependencies if any
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt]; then pip install -r requirements.txt; fi
          
