name: MyWorkflow

on:
  pull_request:
  push:
    branches: [main]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - name: Print a greeting
        run: |
          echo "Hello There"

      # This is where I checkout my code
      - name: Check out code
        uses: actions/checkout@v4

      - name: Print content of repo
        run: |
          ls

      # This is where I install Python
      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check Python version
        run: |
          python --version

      # Installing dependencies if any
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      # Begin tests
      - name: Begin test
        run: |
          pytest

      # This is where we access the hidden repo
      - name: Checkout Hidden Repo
        uses: actions/checkout@v4
        with:
          repository: bryan-NP/UOBHidden
          path: hiddenfolder
          token: ${{ secrets.SECRETUOB }}

      # This prints out the hidden files
      - name: Print out hidden things
        run: |
          ls -a
          cd hiddenfolder
          ls -a

      # Send Discord notification
      - name: Send Discord notification
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: ${{ github.repository }} has been successfully deployed.

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.INDEXTOKEN }}
          publish_dir: . #Publish the root directory (where index.html is located)
