name: MyWorkflow

on:
  pull_request:
  push:
    branches: [main]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - name: Print a greeting
        run: echo "Hello There"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Print content of repo
        run: ls

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check Python version
        run: python --version

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run tests
        run: pytest

      # Uncomment to access the hidden repo
      # - name: Check out hidden repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: bryan-NP/UOBHidden
      #     path: hiddenfolder
      #     token: ${{ secrets.SECRETUOB }}

      # Uncomment to print out the hidden files
      # - name: Print hidden files
      #   run: |
      #     ls -a
      #     cd hiddenfolder
      #     ls -a

      - name: Send Discord pending notification
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: Deployment is pending for repository.

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.INDEXTOKEN }}
          publish_dir: ./ # Publish the root directory (where index.html is located)

      - name: Send Discord done notification
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: Deployment for repository has been **successfully deployed**.
